# config.toml
[theme]
base = "light"

# Primary accent color.
primaryColor = "#000080"

# Background color of the app.
backgroundColor = "#ADD8E6"

# Background color used for most interactive widgets.
#secondaryBackgroundColor = "#000080"

# Color used for almost all text.
textColor = "#4B89DC"

